### ISSUE TITLE
http error: 404 | {"msg":"Not found"}

### ISSUE THREAD

**Issue by natsu90** [iron-io/laraworker#3]
What am I missing? Log:
```
[2015-02-23 16:00:52] production.ERROR: exception 'Http_Exception' with message 'http error: 404 | {"msg":"Not found"}' in C:\xampp\htdocs\whatsapp\vendor\iron-io\iron_core\IronCore.class.php:353
Stack trace:
#0 C:\xampp\htdocs\whatsapp\vendor\iron-io\iron_core\IronCore.class.php(344): IronCore->reportHttpError(404, '{"msg":"Not fou...')
#1 C:\xampp\htdocs\whatsapp\vendor\iron-io\iron_core\IronCore.class.php(305): IronCore->callWithRetries()
#2 C:\xampp\htdocs\whatsapp\vendor\iron-io\iron_mq\IronMQ.class.php(273): IronCore->apiCall('POST', 'projects/54e9f8...', Array)
#3 C:\xampp\htdocs\whatsapp\vendor\laravel\framework\src\Illuminate\Queue\IronQueue.php(80): IronMQ->postMessage('ExampleLaraWork...', 'eyJpdiI6InZcL2Z...', Array)
#4 [internal function]: Illuminate\Queue\IronQueue->pushRaw('This is Hello W...', 'ExampleLaraWork...')
#5 C:\xampp\htdocs\whatsapp\vendor\laravel\framework\src\Illuminate\Queue\QueueManager.php(220): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\whatsapp\bootstrap\compiled.php(3265): Illuminate\Queue\QueueManager->__call('pushRaw', Array)
#7 C:\xampp\htdocs\whatsapp\bootstrap\compiled.php(3265): Illuminate\Queue\QueueManager->pushRaw('This is Hello W...', 'ExampleLaraWork...')
#8 C:\xampp\htdocs\whatsapp\app\commands\RunWorker.php(36): Illuminate\Support\Facades\Facade::__callStatic('pushRaw', Array)
#9 C:\xampp\htdocs\whatsapp\app\commands\RunWorker.php(36): Illuminate\Support\Facades\Queue::pushRaw('This is Hello W...', 'ExampleLaraWork...')
#10 C:\xampp\htdocs\whatsapp\vendor\laravel\framework\src\Illuminate\Console\Command.php(112): RunWorker->fire()
#11 C:\xampp\htdocs\whatsapp\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\whatsapp\vendor\laravel\framework\src\Illuminate\Console\Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\whatsapp\vendor\symfony\console\Symfony\Component\Console\Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\whatsapp\vendor\symfony\console\Symfony\Component\Console\Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(RunWorker), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\whatsapp\vendor\symfony\console\Symfony\Component\Console\Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\whatsapp\artisan(59): Symfony\Component\Console\Application->run()
#17 {main} [] []
```

**Comment by thousandsofthem** [comment]
99% it's wrong library version, see https://github.com/iron-io/iron_mq_php#branches for details.
Simply set version to `"iron_mq":"1.*"` and bundle it

**Comment by natsu90** [comment]
@thousandsofthem you're correct. i've sent pr #4
